/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sudoku;

/**
 *
 * @author Larry
 */
public class Game_JFrame_1 extends javax.swing.JFrame {

    /**
     * Creates new form Game_JFrame
     */
    public Game_JFrame_1() {
        initComponents();
        this.game = new Game("NAME_OF_PLAYER_NEEDS_TO_GO_HERE"); // A New_Game_Dialog should be created to get the player's name.
        set_board_values();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1_c1 = new java.awt.Label();
        b1_c2 = new java.awt.Label();
        b1_c3 = new java.awt.Label();
        b1_c4 = new java.awt.Label();
        b1_c5 = new java.awt.Label();
        b1_c6 = new java.awt.Label();
        b1_c7 = new java.awt.Label();
        b1_c8 = new java.awt.Label();
        b1_c9 = new java.awt.Label();
        b2_c1 = new java.awt.Label();
        b2_c2 = new java.awt.Label();
        b2_c3 = new java.awt.Label();
        b2_c4 = new java.awt.Label();
        b2_c5 = new java.awt.Label();
        b2_c6 = new java.awt.Label();
        b2_c7 = new java.awt.Label();
        b2_c8 = new java.awt.Label();
        b2_c9 = new java.awt.Label();
        b3_c1 = new java.awt.Label();
        b3_c2 = new java.awt.Label();
        b3_c3 = new java.awt.Label();
        b3_c4 = new java.awt.Label();
        b3_c5 = new java.awt.Label();
        b3_c6 = new java.awt.Label();
        b3_c7 = new java.awt.Label();
        b3_c8 = new java.awt.Label();
        b3_c9 = new java.awt.Label();
        b4_c1 = new java.awt.Label();
        b4_c2 = new java.awt.Label();
        b4_c3 = new java.awt.Label();
        b4_c4 = new java.awt.Label();
        b4_c5 = new java.awt.Label();
        b4_c6 = new java.awt.Label();
        b4_c7 = new java.awt.Label();
        b4_c8 = new java.awt.Label();
        b4_c9 = new java.awt.Label();
        b5_c1 = new java.awt.Label();
        b5_c2 = new java.awt.Label();
        b5_c3 = new java.awt.Label();
        b5_c4 = new java.awt.Label();
        b5_c5 = new java.awt.Label();
        b5_c6 = new java.awt.Label();
        b5_c7 = new java.awt.Label();
        b5_c8 = new java.awt.Label();
        b5_c9 = new java.awt.Label();
        b6_c1 = new java.awt.Label();
        b6_c2 = new java.awt.Label();
        b6_c3 = new java.awt.Label();
        b6_c4 = new java.awt.Label();
        b6_c5 = new java.awt.Label();
        b6_c6 = new java.awt.Label();
        b6_c7 = new java.awt.Label();
        b6_c8 = new java.awt.Label();
        b6_c9 = new java.awt.Label();
        b7_c1 = new java.awt.Label();
        b7_c2 = new java.awt.Label();
        b7_c3 = new java.awt.Label();
        b7_c4 = new java.awt.Label();
        b7_c5 = new java.awt.Label();
        b7_c6 = new java.awt.Label();
        b7_c7 = new java.awt.Label();
        b7_c8 = new java.awt.Label();
        b7_c9 = new java.awt.Label();
        b8_c1 = new java.awt.Label();
        b8_c2 = new java.awt.Label();
        b8_c3 = new java.awt.Label();
        b8_c4 = new java.awt.Label();
        b8_c5 = new java.awt.Label();
        b8_c6 = new java.awt.Label();
        b8_c7 = new java.awt.Label();
        b8_c8 = new java.awt.Label();
        b8_c9 = new java.awt.Label();
        b9_c1 = new java.awt.Label();
        b9_c2 = new java.awt.Label();
        b9_c3 = new java.awt.Label();
        b9_c4 = new java.awt.Label();
        b9_c5 = new java.awt.Label();
        b9_c6 = new java.awt.Label();
        b9_c7 = new java.awt.Label();
        b9_c8 = new java.awt.Label();
        b9_c9 = new java.awt.Label();
        button_1 = new java.awt.Button();
        button_2 = new java.awt.Button();
        button_3 = new java.awt.Button();
        button_4 = new java.awt.Button();
        button_5 = new java.awt.Button();
        button_6 = new java.awt.Button();
        button_7 = new java.awt.Button();
        button_8 = new java.awt.Button();
        button_9 = new java.awt.Button();
        board_input_field = new java.awt.TextField();
        board_label = new java.awt.Label();
        cell_input_field = new java.awt.TextField();
        cell_label = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));

        b1_c1.setAlignment(java.awt.Label.CENTER);
        b1_c1.setBackground(new java.awt.Color(255, 255, 255));
        b1_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b1_c2.setAlignment(java.awt.Label.CENTER);
        b1_c2.setBackground(new java.awt.Color(255, 255, 255));
        b1_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b1_c3.setAlignment(java.awt.Label.CENTER);
        b1_c3.setBackground(new java.awt.Color(255, 255, 255));
        b1_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b1_c4.setAlignment(java.awt.Label.CENTER);
        b1_c4.setBackground(new java.awt.Color(255, 255, 255));
        b1_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b1_c5.setAlignment(java.awt.Label.CENTER);
        b1_c5.setBackground(new java.awt.Color(255, 255, 255));
        b1_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b1_c6.setAlignment(java.awt.Label.CENTER);
        b1_c6.setBackground(new java.awt.Color(255, 255, 255));
        b1_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b1_c7.setAlignment(java.awt.Label.CENTER);
        b1_c7.setBackground(new java.awt.Color(255, 255, 255));
        b1_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b1_c8.setAlignment(java.awt.Label.CENTER);
        b1_c8.setBackground(new java.awt.Color(255, 255, 255));
        b1_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b1_c9.setAlignment(java.awt.Label.CENTER);
        b1_c9.setBackground(new java.awt.Color(255, 255, 255));
        b1_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c1.setAlignment(java.awt.Label.CENTER);
        b2_c1.setBackground(new java.awt.Color(255, 255, 255));
        b2_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c2.setAlignment(java.awt.Label.CENTER);
        b2_c2.setBackground(new java.awt.Color(255, 255, 255));
        b2_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c3.setAlignment(java.awt.Label.CENTER);
        b2_c3.setBackground(new java.awt.Color(255, 255, 255));
        b2_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c4.setAlignment(java.awt.Label.CENTER);
        b2_c4.setBackground(new java.awt.Color(255, 255, 255));
        b2_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c5.setAlignment(java.awt.Label.CENTER);
        b2_c5.setBackground(new java.awt.Color(255, 255, 255));
        b2_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c6.setAlignment(java.awt.Label.CENTER);
        b2_c6.setBackground(new java.awt.Color(255, 255, 255));
        b2_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c7.setAlignment(java.awt.Label.CENTER);
        b2_c7.setBackground(new java.awt.Color(255, 255, 255));
        b2_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c8.setAlignment(java.awt.Label.CENTER);
        b2_c8.setBackground(new java.awt.Color(255, 255, 255));
        b2_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b2_c9.setAlignment(java.awt.Label.CENTER);
        b2_c9.setBackground(new java.awt.Color(255, 255, 255));
        b2_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c1.setAlignment(java.awt.Label.CENTER);
        b3_c1.setBackground(new java.awt.Color(255, 255, 255));
        b3_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c2.setAlignment(java.awt.Label.CENTER);
        b3_c2.setBackground(new java.awt.Color(255, 255, 255));
        b3_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c3.setAlignment(java.awt.Label.CENTER);
        b3_c3.setBackground(new java.awt.Color(255, 255, 255));
        b3_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c4.setAlignment(java.awt.Label.CENTER);
        b3_c4.setBackground(new java.awt.Color(255, 255, 255));
        b3_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c5.setAlignment(java.awt.Label.CENTER);
        b3_c5.setBackground(new java.awt.Color(255, 255, 255));
        b3_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c6.setAlignment(java.awt.Label.CENTER);
        b3_c6.setBackground(new java.awt.Color(255, 255, 255));
        b3_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c7.setAlignment(java.awt.Label.CENTER);
        b3_c7.setBackground(new java.awt.Color(255, 255, 255));
        b3_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c8.setAlignment(java.awt.Label.CENTER);
        b3_c8.setBackground(new java.awt.Color(255, 255, 255));
        b3_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b3_c9.setAlignment(java.awt.Label.CENTER);
        b3_c9.setBackground(new java.awt.Color(255, 255, 255));
        b3_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c1.setAlignment(java.awt.Label.CENTER);
        b4_c1.setBackground(new java.awt.Color(255, 255, 255));
        b4_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c2.setAlignment(java.awt.Label.CENTER);
        b4_c2.setBackground(new java.awt.Color(255, 255, 255));
        b4_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c3.setAlignment(java.awt.Label.CENTER);
        b4_c3.setBackground(new java.awt.Color(255, 255, 255));
        b4_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c4.setAlignment(java.awt.Label.CENTER);
        b4_c4.setBackground(new java.awt.Color(255, 255, 255));
        b4_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c5.setAlignment(java.awt.Label.CENTER);
        b4_c5.setBackground(new java.awt.Color(255, 255, 255));
        b4_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c6.setAlignment(java.awt.Label.CENTER);
        b4_c6.setBackground(new java.awt.Color(255, 255, 255));
        b4_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c7.setAlignment(java.awt.Label.CENTER);
        b4_c7.setBackground(new java.awt.Color(255, 255, 255));
        b4_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c8.setAlignment(java.awt.Label.CENTER);
        b4_c8.setBackground(new java.awt.Color(255, 255, 255));
        b4_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b4_c9.setAlignment(java.awt.Label.CENTER);
        b4_c9.setBackground(new java.awt.Color(255, 255, 255));
        b4_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c1.setAlignment(java.awt.Label.CENTER);
        b5_c1.setBackground(new java.awt.Color(255, 255, 255));
        b5_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c2.setAlignment(java.awt.Label.CENTER);
        b5_c2.setBackground(new java.awt.Color(255, 255, 255));
        b5_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c3.setAlignment(java.awt.Label.CENTER);
        b5_c3.setBackground(new java.awt.Color(255, 255, 255));
        b5_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c4.setAlignment(java.awt.Label.CENTER);
        b5_c4.setBackground(new java.awt.Color(255, 255, 255));
        b5_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c5.setAlignment(java.awt.Label.CENTER);
        b5_c5.setBackground(new java.awt.Color(255, 255, 255));
        b5_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c6.setAlignment(java.awt.Label.CENTER);
        b5_c6.setBackground(new java.awt.Color(255, 255, 255));
        b5_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c7.setAlignment(java.awt.Label.CENTER);
        b5_c7.setBackground(new java.awt.Color(255, 255, 255));
        b5_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c8.setAlignment(java.awt.Label.CENTER);
        b5_c8.setBackground(new java.awt.Color(255, 255, 255));
        b5_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b5_c9.setAlignment(java.awt.Label.CENTER);
        b5_c9.setBackground(new java.awt.Color(255, 255, 255));
        b5_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c1.setAlignment(java.awt.Label.CENTER);
        b6_c1.setBackground(new java.awt.Color(255, 255, 255));
        b6_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c2.setAlignment(java.awt.Label.CENTER);
        b6_c2.setBackground(new java.awt.Color(255, 255, 255));
        b6_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c3.setAlignment(java.awt.Label.CENTER);
        b6_c3.setBackground(new java.awt.Color(255, 255, 255));
        b6_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c4.setAlignment(java.awt.Label.CENTER);
        b6_c4.setBackground(new java.awt.Color(255, 255, 255));
        b6_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c5.setAlignment(java.awt.Label.CENTER);
        b6_c5.setBackground(new java.awt.Color(255, 255, 255));
        b6_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c6.setAlignment(java.awt.Label.CENTER);
        b6_c6.setBackground(new java.awt.Color(255, 255, 255));
        b6_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c7.setAlignment(java.awt.Label.CENTER);
        b6_c7.setBackground(new java.awt.Color(255, 255, 255));
        b6_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c8.setAlignment(java.awt.Label.CENTER);
        b6_c8.setBackground(new java.awt.Color(255, 255, 255));
        b6_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b6_c9.setAlignment(java.awt.Label.CENTER);
        b6_c9.setBackground(new java.awt.Color(255, 255, 255));
        b6_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c1.setAlignment(java.awt.Label.CENTER);
        b7_c1.setBackground(new java.awt.Color(255, 255, 255));
        b7_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c2.setAlignment(java.awt.Label.CENTER);
        b7_c2.setBackground(new java.awt.Color(255, 255, 255));
        b7_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c3.setAlignment(java.awt.Label.CENTER);
        b7_c3.setBackground(new java.awt.Color(255, 255, 255));
        b7_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c4.setAlignment(java.awt.Label.CENTER);
        b7_c4.setBackground(new java.awt.Color(255, 255, 255));
        b7_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c5.setAlignment(java.awt.Label.CENTER);
        b7_c5.setBackground(new java.awt.Color(255, 255, 255));
        b7_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c6.setAlignment(java.awt.Label.CENTER);
        b7_c6.setBackground(new java.awt.Color(255, 255, 255));
        b7_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c7.setAlignment(java.awt.Label.CENTER);
        b7_c7.setBackground(new java.awt.Color(255, 255, 255));
        b7_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c8.setAlignment(java.awt.Label.CENTER);
        b7_c8.setBackground(new java.awt.Color(255, 255, 255));
        b7_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b7_c9.setAlignment(java.awt.Label.CENTER);
        b7_c9.setBackground(new java.awt.Color(255, 255, 255));
        b7_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c1.setAlignment(java.awt.Label.CENTER);
        b8_c1.setBackground(new java.awt.Color(255, 255, 255));
        b8_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c2.setAlignment(java.awt.Label.CENTER);
        b8_c2.setBackground(new java.awt.Color(255, 255, 255));
        b8_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c3.setAlignment(java.awt.Label.CENTER);
        b8_c3.setBackground(new java.awt.Color(255, 255, 255));
        b8_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c4.setAlignment(java.awt.Label.CENTER);
        b8_c4.setBackground(new java.awt.Color(255, 255, 255));
        b8_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c5.setAlignment(java.awt.Label.CENTER);
        b8_c5.setBackground(new java.awt.Color(255, 255, 255));
        b8_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c6.setAlignment(java.awt.Label.CENTER);
        b8_c6.setBackground(new java.awt.Color(255, 255, 255));
        b8_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c7.setAlignment(java.awt.Label.CENTER);
        b8_c7.setBackground(new java.awt.Color(255, 255, 255));
        b8_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c8.setAlignment(java.awt.Label.CENTER);
        b8_c8.setBackground(new java.awt.Color(255, 255, 255));
        b8_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b8_c9.setAlignment(java.awt.Label.CENTER);
        b8_c9.setBackground(new java.awt.Color(255, 255, 255));
        b8_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c1.setAlignment(java.awt.Label.CENTER);
        b9_c1.setBackground(new java.awt.Color(255, 255, 255));
        b9_c1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c2.setAlignment(java.awt.Label.CENTER);
        b9_c2.setBackground(new java.awt.Color(255, 255, 255));
        b9_c2.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c3.setAlignment(java.awt.Label.CENTER);
        b9_c3.setBackground(new java.awt.Color(255, 255, 255));
        b9_c3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c4.setAlignment(java.awt.Label.CENTER);
        b9_c4.setBackground(new java.awt.Color(255, 255, 255));
        b9_c4.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c5.setAlignment(java.awt.Label.CENTER);
        b9_c5.setBackground(new java.awt.Color(255, 255, 255));
        b9_c5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c6.setAlignment(java.awt.Label.CENTER);
        b9_c6.setBackground(new java.awt.Color(255, 255, 255));
        b9_c6.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c7.setAlignment(java.awt.Label.CENTER);
        b9_c7.setBackground(new java.awt.Color(255, 255, 255));
        b9_c7.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c8.setAlignment(java.awt.Label.CENTER);
        b9_c8.setBackground(new java.awt.Color(255, 255, 255));
        b9_c8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        b9_c9.setAlignment(java.awt.Label.CENTER);
        b9_c9.setBackground(new java.awt.Color(255, 255, 255));
        b9_c9.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        button_1.setLabel("1");

        button_2.setLabel("2");

        button_3.setLabel("3");

        button_4.setLabel("4");

        button_5.setLabel("5");

        button_6.setLabel("6");

        button_7.setLabel("7");

        button_8.setLabel("8");

        button_9.setLabel("9");

        board_input_field.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        board_label.setAlignment(java.awt.Label.CENTER);
        board_label.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        board_label.setText("Block #:");

        cell_input_field.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N

        cell_label.setAlignment(java.awt.Label.CENTER);
        cell_label.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        cell_label.setText("Cell #:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b1_c4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(b1_c7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(b1_c1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b1_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b4_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b7_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b7_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b7_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b2_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b2_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b2_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b2_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b5_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b8_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b8_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b8_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b3_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b3_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b3_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b3_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b3_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(board_label, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(board_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(b3_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cell_label, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cell_input_field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b6_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b6_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b6_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b9_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b9_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b9_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b3_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(b3_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b3_c9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cell_input_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(board_input_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(board_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cell_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b3_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b3_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b3_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b3_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b3_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b3_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b6_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b6_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b6_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b6_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b6_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b6_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b6_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b6_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b6_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b9_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b9_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b9_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b9_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b9_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b9_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(b9_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b9_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(b9_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b1_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b1_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(b1_c1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(b1_c2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(b1_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(b1_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(b1_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(b1_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b4_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b4_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b4_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b4_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b4_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b4_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b4_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b7_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b7_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b7_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b7_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b7_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b7_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b7_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b7_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b7_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b2_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b2_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b2_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b2_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b2_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b2_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b2_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b2_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b2_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b5_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b5_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b5_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b5_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b5_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b5_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b5_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b5_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b5_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b8_c3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b8_c6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b8_c9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b8_c2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b8_c5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b8_c8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b8_c1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b8_c4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(b8_c7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_JFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_JFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_JFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_JFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    private Game game;
    
    public void set_game (Game a_game)
        {
            this.game = a_game;
        }

    private void set_board_values()
            // Sets the text for all of the labels that represent the board.
        {
            b1_c1.setText("" + game.board.four_dimensional_playable[0][0][0][0]); 
            b1_c2.setText("" + game.board.four_dimensional_playable[0][0][0][1]); 
            b1_c3.setText("" + game.board.four_dimensional_playable[0][0][0][2]); 
            b1_c4.setText("" + game.board.four_dimensional_playable[0][0][1][0]); 
            b1_c5.setText("" + game.board.four_dimensional_playable[0][0][1][1]); 
            b1_c6.setText("" + game.board.four_dimensional_playable[0][0][1][2]); 
            b1_c7.setText("" + game.board.four_dimensional_playable[0][0][2][0]); 
            b1_c8.setText("" + game.board.four_dimensional_playable[0][0][2][1]); 
            b1_c9.setText("" + game.board.four_dimensional_playable[0][0][2][2]); 

            b2_c1.setText("" + game.board.four_dimensional_playable[0][1][0][0]); 
            b2_c2.setText("" + game.board.four_dimensional_playable[0][1][0][1]); 
            b2_c3.setText("" + game.board.four_dimensional_playable[0][1][0][2]); 
            b2_c4.setText("" + game.board.four_dimensional_playable[0][1][1][0]); 
            b2_c5.setText("" + game.board.four_dimensional_playable[0][1][1][1]); 
            b2_c6.setText("" + game.board.four_dimensional_playable[0][1][1][2]); 
            b2_c7.setText("" + game.board.four_dimensional_playable[0][1][2][0]); 
            b2_c8.setText("" + game.board.four_dimensional_playable[0][1][2][1]); 
            b2_c9.setText("" + game.board.four_dimensional_playable[0][1][2][2]); 

            b3_c1.setText("" + game.board.four_dimensional_playable[0][2][0][0]); 
            b3_c2.setText("" + game.board.four_dimensional_playable[0][2][0][1]); 
            b3_c3.setText("" + game.board.four_dimensional_playable[0][2][0][2]); 
            b3_c4.setText("" + game.board.four_dimensional_playable[0][2][1][0]); 
            b3_c5.setText("" + game.board.four_dimensional_playable[0][2][1][1]); 
            b3_c6.setText("" + game.board.four_dimensional_playable[0][2][1][2]); 
            b3_c7.setText("" + game.board.four_dimensional_playable[0][2][2][0]); 
            b3_c8.setText("" + game.board.four_dimensional_playable[0][2][2][1]); 
            b3_c9.setText("" + game.board.four_dimensional_playable[0][2][2][2]); 

            b4_c1.setText("" + game.board.four_dimensional_playable[1][0][0][0]); 
            b4_c2.setText("" + game.board.four_dimensional_playable[1][0][0][1]); 
            b4_c3.setText("" + game.board.four_dimensional_playable[1][0][0][2]); 
            b4_c4.setText("" + game.board.four_dimensional_playable[1][0][1][0]); 
            b4_c5.setText("" + game.board.four_dimensional_playable[1][0][1][1]); 
            b4_c6.setText("" + game.board.four_dimensional_playable[1][0][1][2]); 
            b4_c7.setText("" + game.board.four_dimensional_playable[1][0][2][0]); 
            b4_c8.setText("" + game.board.four_dimensional_playable[1][0][2][1]); 
            b4_c9.setText("" + game.board.four_dimensional_playable[1][0][2][2]); 

            b5_c1.setText("" + game.board.four_dimensional_playable[1][1][0][0]); 
            b5_c2.setText("" + game.board.four_dimensional_playable[1][1][0][1]); 
            b5_c3.setText("" + game.board.four_dimensional_playable[1][1][0][2]); 
            b5_c4.setText("" + game.board.four_dimensional_playable[1][1][1][0]); 
            b5_c5.setText("" + game.board.four_dimensional_playable[1][1][1][1]); 
            b5_c6.setText("" + game.board.four_dimensional_playable[1][1][1][2]); 
            b5_c7.setText("" + game.board.four_dimensional_playable[1][1][2][0]); 
            b5_c8.setText("" + game.board.four_dimensional_playable[1][1][2][1]); 
            b5_c9.setText("" + game.board.four_dimensional_playable[1][1][2][2]); 

            b6_c1.setText("" + game.board.four_dimensional_playable[1][2][0][0]); 
            b6_c2.setText("" + game.board.four_dimensional_playable[1][2][0][1]); 
            b6_c3.setText("" + game.board.four_dimensional_playable[1][2][0][2]); 
            b6_c4.setText("" + game.board.four_dimensional_playable[1][2][1][0]); 
            b6_c5.setText("" + game.board.four_dimensional_playable[1][2][1][1]); 
            b6_c6.setText("" + game.board.four_dimensional_playable[1][2][1][2]); 
            b6_c7.setText("" + game.board.four_dimensional_playable[1][2][2][0]); 
            b6_c8.setText("" + game.board.four_dimensional_playable[1][2][2][1]); 
            b6_c9.setText("" + game.board.four_dimensional_playable[1][2][2][2]); 

            b7_c1.setText("" + game.board.four_dimensional_playable[2][0][0][0]); 
            b7_c2.setText("" + game.board.four_dimensional_playable[2][0][0][1]); 
            b7_c3.setText("" + game.board.four_dimensional_playable[2][0][0][2]); 
            b7_c4.setText("" + game.board.four_dimensional_playable[2][0][1][0]); 
            b7_c5.setText("" + game.board.four_dimensional_playable[2][0][1][1]); 
            b7_c6.setText("" + game.board.four_dimensional_playable[2][0][1][2]); 
            b7_c7.setText("" + game.board.four_dimensional_playable[2][0][2][0]); 
            b7_c8.setText("" + game.board.four_dimensional_playable[2][0][2][1]); 
            b7_c9.setText("" + game.board.four_dimensional_playable[2][0][2][2]); 

            b8_c1.setText("" + game.board.four_dimensional_playable[2][1][0][0]); 
            b8_c2.setText("" + game.board.four_dimensional_playable[2][1][0][1]); 
            b8_c3.setText("" + game.board.four_dimensional_playable[2][1][0][2]); 
            b8_c4.setText("" + game.board.four_dimensional_playable[2][1][1][0]); 
            b8_c5.setText("" + game.board.four_dimensional_playable[2][1][1][1]); 
            b8_c6.setText("" + game.board.four_dimensional_playable[2][1][1][2]); 
            b8_c7.setText("" + game.board.four_dimensional_playable[2][1][2][0]); 
            b8_c8.setText("" + game.board.four_dimensional_playable[2][1][2][1]); 
            b8_c9.setText("" + game.board.four_dimensional_playable[2][1][2][2]); 

            b9_c1.setText("" + game.board.four_dimensional_playable[2][2][0][0]); 
            b9_c2.setText("" + game.board.four_dimensional_playable[2][2][0][1]); 
            b9_c3.setText("" + game.board.four_dimensional_playable[2][2][0][2]); 
            b9_c4.setText("" + game.board.four_dimensional_playable[2][2][1][0]); 
            b9_c5.setText("" + game.board.four_dimensional_playable[2][2][1][1]); 
            b9_c6.setText("" + game.board.four_dimensional_playable[2][2][1][2]); 
            b9_c7.setText("" + game.board.four_dimensional_playable[2][2][2][0]); 
            b9_c8.setText("" + game.board.four_dimensional_playable[2][2][2][1]); 
            b9_c9.setText("" + game.board.four_dimensional_playable[2][2][2][2]);       
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label b1_c1;
    private java.awt.Label b1_c2;
    private java.awt.Label b1_c3;
    private java.awt.Label b1_c4;
    private java.awt.Label b1_c5;
    private java.awt.Label b1_c6;
    private java.awt.Label b1_c7;
    private java.awt.Label b1_c8;
    private java.awt.Label b1_c9;
    private java.awt.Label b2_c1;
    private java.awt.Label b2_c2;
    private java.awt.Label b2_c3;
    private java.awt.Label b2_c4;
    private java.awt.Label b2_c5;
    private java.awt.Label b2_c6;
    private java.awt.Label b2_c7;
    private java.awt.Label b2_c8;
    private java.awt.Label b2_c9;
    private java.awt.Label b3_c1;
    private java.awt.Label b3_c2;
    private java.awt.Label b3_c3;
    private java.awt.Label b3_c4;
    private java.awt.Label b3_c5;
    private java.awt.Label b3_c6;
    private java.awt.Label b3_c7;
    private java.awt.Label b3_c8;
    private java.awt.Label b3_c9;
    private java.awt.Label b4_c1;
    private java.awt.Label b4_c2;
    private java.awt.Label b4_c3;
    private java.awt.Label b4_c4;
    private java.awt.Label b4_c5;
    private java.awt.Label b4_c6;
    private java.awt.Label b4_c7;
    private java.awt.Label b4_c8;
    private java.awt.Label b4_c9;
    private java.awt.Label b5_c1;
    private java.awt.Label b5_c2;
    private java.awt.Label b5_c3;
    private java.awt.Label b5_c4;
    private java.awt.Label b5_c5;
    private java.awt.Label b5_c6;
    private java.awt.Label b5_c7;
    private java.awt.Label b5_c8;
    private java.awt.Label b5_c9;
    private java.awt.Label b6_c1;
    private java.awt.Label b6_c2;
    private java.awt.Label b6_c3;
    private java.awt.Label b6_c4;
    private java.awt.Label b6_c5;
    private java.awt.Label b6_c6;
    private java.awt.Label b6_c7;
    private java.awt.Label b6_c8;
    private java.awt.Label b6_c9;
    private java.awt.Label b7_c1;
    private java.awt.Label b7_c2;
    private java.awt.Label b7_c3;
    private java.awt.Label b7_c4;
    private java.awt.Label b7_c5;
    private java.awt.Label b7_c6;
    private java.awt.Label b7_c7;
    private java.awt.Label b7_c8;
    private java.awt.Label b7_c9;
    private java.awt.Label b8_c1;
    private java.awt.Label b8_c2;
    private java.awt.Label b8_c3;
    private java.awt.Label b8_c4;
    private java.awt.Label b8_c5;
    private java.awt.Label b8_c6;
    private java.awt.Label b8_c7;
    private java.awt.Label b8_c8;
    private java.awt.Label b8_c9;
    private java.awt.Label b9_c1;
    private java.awt.Label b9_c2;
    private java.awt.Label b9_c3;
    private java.awt.Label b9_c4;
    private java.awt.Label b9_c5;
    private java.awt.Label b9_c6;
    private java.awt.Label b9_c7;
    private java.awt.Label b9_c8;
    private java.awt.Label b9_c9;
    private java.awt.TextField board_input_field;
    private java.awt.Label board_label;
    private java.awt.Button button_1;
    private java.awt.Button button_2;
    private java.awt.Button button_3;
    private java.awt.Button button_4;
    private java.awt.Button button_5;
    private java.awt.Button button_6;
    private java.awt.Button button_7;
    private java.awt.Button button_8;
    private java.awt.Button button_9;
    private java.awt.TextField cell_input_field;
    private java.awt.Label cell_label;
    // End of variables declaration//GEN-END:variables
}
